// ============================================================================
// GENERATOR - Resume, cover letter, and portfolio generation
// ============================================================================

const Generator = {
    async generateResume(profile, jdData, aiProvider, mode) {
        try {
            // Get tailored content from AI
            const aiResult = await AIIntegration.tailorResume(aiProvider, profile, jdData, mode);
            
            // Parse AI response
            let tailored;
            try {
                tailored = JSON.parse(aiResult.tailored);
            } catch {
                tailored = { full_resume: aiResult.tailored };
            }
            
            // Create DOCX
            const doc = new docx.Document({
                sections: [{
                    properties: {},
                    children: [
                        new docx.Paragraph({
                            text: profile.name || 'Your Name',
                            style: 'Heading1',
                            alignment: docx.AlignmentType.CENTER
                        }),
                        new docx.Paragraph({
                            text: profile.email || '',
                            alignment: docx.AlignmentType.CENTER
                        }),
                        new docx.Paragraph({ text: '', spacing: { line: 240 } }),
                        new docx.Paragraph({
                            text: tailored.summary || tailored.full_resume || 'Resume content',
                            spacing: { line: 240 }
                        })
                    ]
                }]
            });
            
            const docxBlob = await docx.Packer.toBlob(doc);
            
            // Create PDF
            const pdfDoc = new PDFDocument();
            pdfDoc.fontSize(24).text(profile.name, { align: 'center' });
            pdfDoc.fontSize(12).text(profile.email || '', { align: 'center' });
            pdfDoc.moveDown();
            pdfDoc.fontSize(10).text(tailored.summary || tailored.full_resume || 'Resume content', { wrap: true });
            
            const pdfBlob = await new Promise(resolve => {
                const chunks = [];
                pdfDoc.on('data', chunk => chunks.push(chunk));
                pdfDoc.on('end', () => resolve(new Blob(chunks, { type: 'application/pdf' })));
                pdfDoc.end();
            });
            
            return {
                success: true,
                docx: docxBlob,
                pdf: pdfBlob,
                cost: aiResult.cost,
                provider: aiProvider
            };
        } catch (error) {
            return { success: false, error: error.message };
        }
    },
    
    async generateCoverLetter(profile, jobTitle, company, jdData, aiProvider, mode) {
        try {
            const prompt = `Write a professional cover letter for ${profile.name} applying for ${jobTitle} at ${company}. Keep it concise (under 250 words). Job description: ${jdData}`;
            
            const aiResult = await AIIntegration.tailorResume(aiProvider, { name: profile.name }, prompt, mode);
            
            // Create DOCX
            const doc = new docx.Document({
                sections: [{
                    properties: {},
                    children: [
                        new docx.Paragraph({
                            text: profile.name,
                            alignment: docx.AlignmentType.CENTER,
                            style: 'Heading2'
                        }),
                        new docx.Paragraph({ text: '', spacing: { line: 240 } }),
                        new docx.Paragraph({
                            text: aiResult.tailored,
                            spacing: { line: 240 }
                        })
                    ]
                }]
            });
            
            const docxBlob = await docx.Packer.toBlob(doc);
            
            return {
                success: true,
                docx: docxBlob,
                cost: aiResult.cost,
                provider: aiProvider
            };
        } catch (error) {
            return { success: false, error: error.message };
        }
    },
    
    generateJobDetails(company, position, jdData) {
        const content = `# Job Application Details

## Position
**${position}**

## Company
**${company}**

## Job Description
${jdData}

## Generated At
${new Date().toISOString()}

---
Generated by Resume Engine Pro
`;
        return new Blob([content], { type: 'text/markdown' });
    },
    
    async generatePortfolio(profile, template = 'minimalist') {
        try {
            const html = PortfolioTemplates.generatePortfolio(profile, template, 0);
            return {
                success: true,
                html: html,
                template: template
            };
        } catch (error) {
            return { success: false, error: error.message };
        }
    },
    
    async bulkGenerate(profiles, jdData, aiProvider, mode) {
        const results = [];
        
        for (const profile of profiles) {
            try {
                const resume = await this.generateResume(profile, jdData, aiProvider, mode);
                results.push({
                    profile: profile.name,
                    success: resume.success,
                    resume: resume.docx,
                    cost: resume.cost
                });
            } catch (error) {
                results.push({
                    profile: profile.name,
                    success: false,
                    error: error.message
                });
            }
        }
        
        return results;
    },
    
    downloadFile(blob, filename) {
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        link.click();
        URL.revokeObjectURL(url);
    },
    
    async saveToGitHub(repoName, filename, content) {
        if (!GitHubManager.isAuthenticated()) {
            throw new Error('Not authenticated with GitHub');
        }
        
        const path = `generated/${new Date().toISOString().split('T')[0]}/${filename}`;
        return await GitHubManager.pushFile(repoName, path, content);
    }
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = Generator;
}
